// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	InstanceID  string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID      string `gorm:"column:meta_id" json:"meta_id"`
	UID         string `gorm:"column:uid" json:"uid"`
	VersionID   string `gorm:"column:version_id" json:"version_id"`
	Country     string `gorm:"column:country" json:"country"`
	Countrycode string `gorm:"column:countrycode" json:"countrycode"`
	Street      string `gorm:"column:street" json:"street"`
	PostalCode  string `gorm:"column:postal_code" json:"postal_code"`
	Locality    string `gorm:"column:locality" json:"locality"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
