// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	InstanceID  string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID      string `gorm:"column:meta_id" json:"meta_id"`
	UID         string `gorm:"column:uid" json:"uid"`
	VersionID   string `gorm:"column:version_id" json:"version_id"`
	InScheme    string `gorm:"column:in_scheme" json:"in_scheme"`
	Description string `gorm:"column:description" json:"description"`
	Name        string `gorm:"column:name" json:"name"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
