// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategoryScheme = "category_scheme"

// CategoryScheme mapped from table <category_scheme>
type CategoryScheme struct {
	InstanceID      string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID          string `gorm:"column:meta_id" json:"meta_id"`
	UID             string `gorm:"column:uid" json:"uid"`
	VersionID       string `gorm:"column:version_id" json:"version_id"`
	Name            string `gorm:"column:name" json:"name"`
	Code            string `gorm:"column:code" json:"code"`
	Description     string `gorm:"column:description" json:"description"`
	Logo            string `gorm:"column:logo" json:"logo"`
	Homepage        string `gorm:"column:homepage" json:"homepage"`
	Color           string `gorm:"column:color" json:"color"`
	Orderitemnumber string `gorm:"column:orderitemnumber" json:"orderitemnumber"`
}

// TableName CategoryScheme's table name
func (*CategoryScheme) TableName() string {
	return TableNameCategoryScheme
}
