// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategoryIspartof = "category_ispartof"

// CategoryIspartof mapped from table <category_ispartof>
type CategoryIspartof struct {
	Category1InstanceID string `gorm:"column:category1_instance_id;primaryKey" json:"category1_instance_id"`
	Category2InstanceID string `gorm:"column:category2_instance_id;primaryKey" json:"category2_instance_id"`
}

// TableName CategoryIspartof's table name
func (*CategoryIspartof) TableName() string {
	return TableNameCategoryIspartof
}
