// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCategoryHastopconcept = "category_hastopconcept"

// CategoryHastopconcept mapped from table <category_hastopconcept>
type CategoryHastopconcept struct {
	CategorySchemeInstanceID string `gorm:"column:category_scheme_instance_id;primaryKey" json:"category_scheme_instance_id"`
	CategoryInstanceID       string `gorm:"column:category_instance_id;primaryKey" json:"category_instance_id"`
}

// TableName CategoryHastopconcept's table name
func (*CategoryHastopconcept) TableName() string {
	return TableNameCategoryHastopconcept
}
