// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContactpointElement = "contactpoint_element"

// ContactpointElement mapped from table <contactpoint_element>
type ContactpointElement struct {
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
	ElementInstanceID      string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName ContactpointElement's table name
func (*ContactpointElement) TableName() string {
	return TableNameContactpointElement
}
