// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContactpoint = "contactpoint"

// Contactpoint mapped from table <contactpoint>
type Contactpoint struct {
	InstanceID string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string `gorm:"column:meta_id" json:"meta_id"`
	UID        string `gorm:"column:uid" json:"uid"`
	VersionID  string `gorm:"column:version_id" json:"version_id"`
	Role       string `gorm:"column:role" json:"role"`
}

// TableName Contactpoint's table name
func (*Contactpoint) TableName() string {
	return TableNameContactpoint
}
