// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductPublisher = "dataproduct_publisher"

// DataproductPublisher mapped from table <dataproduct_publisher>
type DataproductPublisher struct {
	DataproductInstanceID  string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
	OrganizationInstanceID string `gorm:"column:organization_instance_id;primaryKey" json:"organization_instance_id"`
}

// TableName DataproductPublisher's table name
func (*DataproductPublisher) TableName() string {
	return TableNameDataproductPublisher
}
