// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductTitle = "dataproduct_title"

// DataproductTitle mapped from table <dataproduct_title>
type DataproductTitle struct {
	InstanceID            string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID                string `gorm:"column:meta_id" json:"meta_id"`
	UID                   string `gorm:"column:uid" json:"uid"`
	VersionID             string `gorm:"column:version_id" json:"version_id"`
	Title                 string `gorm:"column:title" json:"title"`
	Lang                  string `gorm:"column:lang" json:"lang"`
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;not null" json:"dataproduct_instance_id"`
}

// TableName DataproductTitle's table name
func (*DataproductTitle) TableName() string {
	return TableNameDataproductTitle
}
