// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductCategory = "dataproduct_category"

// DataproductCategory mapped from table <dataproduct_category>
type DataproductCategory struct {
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
	CategoryInstanceID    string `gorm:"column:category_instance_id;primaryKey" json:"category_instance_id"`
}

// TableName DataproductCategory's table name
func (*DataproductCategory) TableName() string {
	return TableNameDataproductCategory
}
