// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductProvenance = "dataproduct_provenance"

// DataproductProvenance mapped from table <dataproduct_provenance>
type DataproductProvenance struct {
	InstanceID            string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID                string `gorm:"column:meta_id" json:"meta_id"`
	UID                   string `gorm:"column:uid" json:"uid"`
	VersionID             string `gorm:"column:version_id" json:"version_id"`
	Provenance            string `gorm:"column:provenance" json:"provenance"`
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;not null" json:"dataproduct_instance_id"`
}

// TableName DataproductProvenance's table name
func (*DataproductProvenance) TableName() string {
	return TableNameDataproductProvenance
}
