// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductDescription = "dataproduct_description"

// DataproductDescription mapped from table <dataproduct_description>
type DataproductDescription struct {
	InstanceID            string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID                string `gorm:"column:meta_id" json:"meta_id"`
	UID                   string `gorm:"column:uid" json:"uid"`
	VersionID             string `gorm:"column:version_id" json:"version_id"`
	Description           string `gorm:"column:description" json:"description"`
	Lang                  string `gorm:"column:lang" json:"lang"`
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;not null" json:"dataproduct_instance_id"`
}

// TableName DataproductDescription's table name
func (*DataproductDescription) TableName() string {
	return TableNameDataproductDescription
}
