// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductRelation = "dataproduct_relation"

// DataproductRelation mapped from table <dataproduct_relation>
type DataproductRelation struct {
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
	EntityInstanceID      string `gorm:"column:entity_instance_id;not null" json:"entity_instance_id"`
	ResourceEntity        string `gorm:"column:resource_entity;not null" json:"resource_entity"`
}

// TableName DataproductRelation's table name
func (*DataproductRelation) TableName() string {
	return TableNameDataproductRelation
}
