// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductIdentifier = "dataproduct_identifier"

// DataproductIdentifier mapped from table <dataproduct_identifier>
type DataproductIdentifier struct {
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
	IdentifierInstanceID  string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName DataproductIdentifier's table name
func (*DataproductIdentifier) TableName() string {
	return TableNameDataproductIdentifier
}
