// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductTemporal = "dataproduct_temporal"

// DataproductTemporal mapped from table <dataproduct_temporal>
type DataproductTemporal struct {
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
	TemporalInstanceID    string `gorm:"column:temporal_instance_id;primaryKey" json:"temporal_instance_id"`
}

// TableName DataproductTemporal's table name
func (*DataproductTemporal) TableName() string {
	return TableNameDataproductTemporal
}
