// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDataproduct = "dataproduct"

// Dataproduct mapped from table <dataproduct>
type Dataproduct struct {
	InstanceID           string    `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID               string    `gorm:"column:meta_id" json:"meta_id"`
	UID                  string    `gorm:"column:uid" json:"uid"`
	VersionID            string    `gorm:"column:version_id" json:"version_id"`
	Identifier           string    `gorm:"column:identifier" json:"identifier"`
	Created              time.Time `gorm:"column:created" json:"created"`
	Issued               time.Time `gorm:"column:issued" json:"issued"`
	Modified             time.Time `gorm:"column:modified" json:"modified"`
	Versioninfo          string    `gorm:"column:versioninfo" json:"versioninfo"`
	Type                 string    `gorm:"column:type" json:"type"`
	Accrualperiodicity   string    `gorm:"column:accrualperiodicity" json:"accrualperiodicity"`
	Keywords             string    `gorm:"column:keywords" json:"keywords"`
	Accessright          string    `gorm:"column:accessright" json:"accessright"`
	Documentation        string    `gorm:"column:documentation" json:"documentation"`
	Qualityassurance     string    `gorm:"column:qualityassurance" json:"qualityassurance"`
	HasQualityAnnotation string    `gorm:"column:has_quality_annotation" json:"has_quality_annotation"`
}

// TableName Dataproduct's table name
func (*Dataproduct) TableName() string {
	return TableNameDataproduct
}
