// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductContactpoint = "dataproduct_contactpoint"

// DataproductContactpoint mapped from table <dataproduct_contactpoint>
type DataproductContactpoint struct {
	DataproductInstanceID  string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName DataproductContactpoint's table name
func (*DataproductContactpoint) TableName() string {
	return TableNameDataproductContactpoint
}
