// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductSpatial = "dataproduct_spatial"

// DataproductSpatial mapped from table <dataproduct_spatial>
type DataproductSpatial struct {
	DataproductInstanceID string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
	SpatialInstanceID     string `gorm:"column:spatial_instance_id;primaryKey" json:"spatial_instance_id"`
}

// TableName DataproductSpatial's table name
func (*DataproductSpatial) TableName() string {
	return TableNameDataproductSpatial
}
