// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductHaspart = "dataproduct_haspart"

// DataproductHaspart mapped from table <dataproduct_haspart>
type DataproductHaspart struct {
	Dataproduct1InstanceID string `gorm:"column:dataproduct1_instance_id;primaryKey" json:"dataproduct1_instance_id"`
	Dataproduct2InstanceID string `gorm:"column:dataproduct2_instance_id;primaryKey" json:"dataproduct2_instance_id"`
}

// TableName DataproductHaspart's table name
func (*DataproductHaspart) TableName() string {
	return TableNameDataproductHaspart
}
