// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataproductIspartof = "dataproduct_ispartof"

// DataproductIspartof mapped from table <dataproduct_ispartof>
type DataproductIspartof struct {
	Dataproduct1InstanceID string `gorm:"column:dataproduct1_instance_id;primaryKey" json:"dataproduct1_instance_id"`
	Dataproduct2InstanceID string `gorm:"column:dataproduct2_instance_id;primaryKey" json:"dataproduct2_instance_id"`
}

// TableName DataproductIspartof's table name
func (*DataproductIspartof) TableName() string {
	return TableNameDataproductIspartof
}
