// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDistributionDescription = "distribution_description"

// DistributionDescription mapped from table <distribution_description>
type DistributionDescription struct {
	InstanceID             string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID                 string `gorm:"column:meta_id" json:"meta_id"`
	UID                    string `gorm:"column:uid" json:"uid"`
	VersionID              string `gorm:"column:version_id" json:"version_id"`
	Description            string `gorm:"column:description" json:"description"`
	Lang                   string `gorm:"column:lang" json:"lang"`
	DistributionInstanceID string `gorm:"column:distribution_instance_id;not null" json:"distribution_instance_id"`
}

// TableName DistributionDescription's table name
func (*DistributionDescription) TableName() string {
	return TableNameDistributionDescription
}
