// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDistribution = "distribution"

// Distribution mapped from table <distribution>
type Distribution struct {
	InstanceID string    `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string    `gorm:"column:meta_id" json:"meta_id"`
	UID        string    `gorm:"column:uid" json:"uid"`
	VersionID  string    `gorm:"column:version_id" json:"version_id"`
	Issued     time.Time `gorm:"column:issued" json:"issued"`
	Modified   time.Time `gorm:"column:modified" json:"modified"`
	Type       string    `gorm:"column:type" json:"type"`
	Format     string    `gorm:"column:format" json:"format"`
	License    string    `gorm:"column:license" json:"license"`
	Datapolicy string    `gorm:"column:datapolicy" json:"datapolicy"`
}

// TableName Distribution's table name
func (*Distribution) TableName() string {
	return TableNameDistribution
}
