// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDistributionTitle = "distribution_title"

// DistributionTitle mapped from table <distribution_title>
type DistributionTitle struct {
	InstanceID             string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID                 string `gorm:"column:meta_id" json:"meta_id"`
	UID                    string `gorm:"column:uid" json:"uid"`
	VersionID              string `gorm:"column:version_id" json:"version_id"`
	Title                  string `gorm:"column:title" json:"title"`
	Lang                   string `gorm:"column:lang" json:"lang"`
	DistributionInstanceID string `gorm:"column:distribution_instance_id;not null" json:"distribution_instance_id"`
}

// TableName DistributionTitle's table name
func (*DistributionTitle) TableName() string {
	return TableNameDistributionTitle
}
