// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDistributionElement = "distribution_element"

// DistributionElement mapped from table <distribution_element>
type DistributionElement struct {
	DistributionInstanceID string `gorm:"column:distribution_instance_id;primaryKey" json:"distribution_instance_id"`
	ElementInstanceID      string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName DistributionElement's table name
func (*DistributionElement) TableName() string {
	return TableNameDistributionElement
}
