// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDistributionDataproduct = "distribution_dataproduct"

// DistributionDataproduct mapped from table <distribution_dataproduct>
type DistributionDataproduct struct {
	DistributionInstanceID string `gorm:"column:distribution_instance_id;primaryKey" json:"distribution_instance_id"`
	DataproductInstanceID  string `gorm:"column:dataproduct_instance_id;primaryKey" json:"dataproduct_instance_id"`
}

// TableName DistributionDataproduct's table name
func (*DistributionDataproduct) TableName() string {
	return TableNameDistributionDataproduct
}
