// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEdmEntityID = "edm_entity_id"

// EdmEntityID mapped from table <edm_entity_id>
type EdmEntityID struct {
	MetaID    string `gorm:"column:meta_id;primaryKey" json:"meta_id"`
	TableName string `gorm:"column:table_name" json:"table_name"`
}
