// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameElement = "element"

// Element mapped from table <element>
type Element struct {
	InstanceID string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string `gorm:"column:meta_id" json:"meta_id"`
	UID        string `gorm:"column:uid" json:"uid"`
	VersionID  string `gorm:"column:version_id" json:"version_id"`
	Type       string `gorm:"column:type" json:"type"`
	Value      string `gorm:"column:value" json:"value"`
}

// TableName Element's table name
func (*Element) TableName() string {
	return TableNameElement
}
