// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipmentCategory = "equipment_category"

// EquipmentCategory mapped from table <equipment_category>
type EquipmentCategory struct {
	CategoryInstanceID  string `gorm:"column:category_instance_id;primaryKey" json:"category_instance_id"`
	EquipmentInstanceID string `gorm:"column:equipment_instance_id;primaryKey" json:"equipment_instance_id"`
}

// TableName EquipmentCategory's table name
func (*EquipmentCategory) TableName() string {
	return TableNameEquipmentCategory
}
