// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipmentRelation = "equipment_relation"

// EquipmentRelation mapped from table <equipment_relation>
type EquipmentRelation struct {
	EquipmentInstanceID string `gorm:"column:equipment_instance_id;primaryKey" json:"equipment_instance_id"`
	EntityInstanceID    string `gorm:"column:entity_instance_id;not null" json:"entity_instance_id"`
	ResourceEntity      string `gorm:"column:resource_entity;not null" json:"resource_entity"`
}

// TableName EquipmentRelation's table name
func (*EquipmentRelation) TableName() string {
	return TableNameEquipmentRelation
}
