// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipmentContactpoint = "equipment_contactpoint"

// EquipmentContactpoint mapped from table <equipment_contactpoint>
type EquipmentContactpoint struct {
	EquipmentInstanceID    string `gorm:"column:equipment_instance_id;primaryKey" json:"equipment_instance_id"`
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName EquipmentContactpoint's table name
func (*EquipmentContactpoint) TableName() string {
	return TableNameEquipmentContactpoint
}
