// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipmentElement = "equipment_element"

// EquipmentElement mapped from table <equipment_element>
type EquipmentElement struct {
	EquipmentInstanceID string `gorm:"column:equipment_instance_id;primaryKey" json:"equipment_instance_id"`
	ElementInstanceID   string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName EquipmentElement's table name
func (*EquipmentElement) TableName() string {
	return TableNameEquipmentElement
}
