// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipmentTemporal = "equipment_temporal"

// EquipmentTemporal mapped from table <equipment_temporal>
type EquipmentTemporal struct {
	EquipmentInstanceID string `gorm:"column:equipment_instance_id;primaryKey" json:"equipment_instance_id"`
	TemporalInstanceID  string `gorm:"column:temporal_instance_id;primaryKey" json:"temporal_instance_id"`
}

// TableName EquipmentTemporal's table name
func (*EquipmentTemporal) TableName() string {
	return TableNameEquipmentTemporal
}
