// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipmentIspartof = "equipment_ispartof"

// EquipmentIspartof mapped from table <equipment_ispartof>
type EquipmentIspartof struct {
	EquipmentInstanceID string `gorm:"column:equipment_instance_id;primaryKey" json:"equipment_instance_id"`
	EntityInstanceID    string `gorm:"column:entity_instance_id;not null" json:"entity_instance_id"`
	ResourceEntity      string `gorm:"column:resource_entity;not null" json:"resource_entity"`
}

// TableName EquipmentIspartof's table name
func (*EquipmentIspartof) TableName() string {
	return TableNameEquipmentIspartof
}
