// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipment = "equipment"

// Equipment mapped from table <equipment>
type Equipment struct {
	InstanceID   string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID       string `gorm:"column:meta_id" json:"meta_id"`
	UID          string `gorm:"column:uid" json:"uid"`
	VersionID    string `gorm:"column:version_id" json:"version_id"`
	Identifier   string `gorm:"column:identifier" json:"identifier"`
	Description  string `gorm:"column:description" json:"description"`
	Name         string `gorm:"column:name" json:"name"`
	Type         string `gorm:"column:type" json:"type"`
	Creator      string `gorm:"column:creator" json:"creator"`
	Keywords     string `gorm:"column:keywords" json:"keywords"`
	Pageurl      string `gorm:"column:pageurl" json:"pageurl"`
	Filter       string `gorm:"column:filter" json:"filter"`
	Dynamicrange string `gorm:"column:dynamicrange" json:"dynamicrange"`
	Orientation  string `gorm:"column:orientation" json:"orientation"`
	Resolution   string `gorm:"column:resolution" json:"resolution"`
	Sampleperiod string `gorm:"column:sampleperiod" json:"sampleperiod"`
	Serialnumber string `gorm:"column:serialnumber" json:"serialnumber"`
}

// TableName Equipment's table name
func (*Equipment) TableName() string {
	return TableNameEquipment
}
