// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEquipmentSpatial = "equipment_spatial"

// EquipmentSpatial mapped from table <equipment_spatial>
type EquipmentSpatial struct {
	EquipmentInstanceID string `gorm:"column:equipment_instance_id;primaryKey" json:"equipment_instance_id"`
	SpatialInstanceID   string `gorm:"column:spatial_instance_id;primaryKey" json:"spatial_instance_id"`
}

// TableName EquipmentSpatial's table name
func (*EquipmentSpatial) TableName() string {
	return TableNameEquipmentSpatial
}
