// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFacilityElement = "facility_element"

// FacilityElement mapped from table <facility_element>
type FacilityElement struct {
	FacilityInstanceID string `gorm:"column:facility_instance_id;primaryKey" json:"facility_instance_id"`
	ElementInstanceID  string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName FacilityElement's table name
func (*FacilityElement) TableName() string {
	return TableNameFacilityElement
}
