// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFacilityContactpoint = "facility_contactpoint"

// FacilityContactpoint mapped from table <facility_contactpoint>
type FacilityContactpoint struct {
	FacilityInstanceID     string `gorm:"column:facility_instance_id;primaryKey" json:"facility_instance_id"`
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName FacilityContactpoint's table name
func (*FacilityContactpoint) TableName() string {
	return TableNameFacilityContactpoint
}
