// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFacilitySpatial = "facility_spatial"

// FacilitySpatial mapped from table <facility_spatial>
type FacilitySpatial struct {
	FacilityInstanceID string `gorm:"column:facility_instance_id;primaryKey" json:"facility_instance_id"`
	SpatialInstanceID  string `gorm:"column:spatial_instance_id;primaryKey" json:"spatial_instance_id"`
}

// TableName FacilitySpatial's table name
func (*FacilitySpatial) TableName() string {
	return TableNameFacilitySpatial
}
