// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFacilityIspartof = "facility_ispartof"

// FacilityIspartof mapped from table <facility_ispartof>
type FacilityIspartof struct {
	Facility1InstanceID string `gorm:"column:facility1_instance_id;primaryKey" json:"facility1_instance_id"`
	Facility2InstanceID string `gorm:"column:facility2_instance_id;primaryKey" json:"facility2_instance_id"`
}

// TableName FacilityIspartof's table name
func (*FacilityIspartof) TableName() string {
	return TableNameFacilityIspartof
}
