// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFacilityAddress = "facility_address"

// FacilityAddress mapped from table <facility_address>
type FacilityAddress struct {
	FacilityInstanceID string `gorm:"column:facility_instance_id;primaryKey" json:"facility_instance_id"`
	AddressInstanceID  string `gorm:"column:address_instance_id;primaryKey" json:"address_instance_id"`
}

// TableName FacilityAddress's table name
func (*FacilityAddress) TableName() string {
	return TableNameFacilityAddress
}
