// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMapping = "mapping"

// Mapping mapped from table <mapping>
type Mapping struct {
	InstanceID     string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID         string `gorm:"column:meta_id" json:"meta_id"`
	UID            string `gorm:"column:uid" json:"uid"`
	VersionID      string `gorm:"column:version_id" json:"version_id"`
	Label          string `gorm:"column:label" json:"label"`
	Variable       string `gorm:"column:variable" json:"variable"`
	Required       bool   `gorm:"column:required" json:"required"`
	Range          string `gorm:"column:range" json:"range"`
	Defaultvalue   string `gorm:"column:defaultvalue" json:"defaultvalue"`
	Minvalue       string `gorm:"column:minvalue" json:"minvalue"`
	Maxvalue       string `gorm:"column:maxvalue" json:"maxvalue"`
	Property       string `gorm:"column:property" json:"property"`
	Valuepattern   string `gorm:"column:valuepattern" json:"valuepattern"`
	ReadOnlyValue  string `gorm:"column:read_only_value" json:"read_only_value"`
	MultipleValues string `gorm:"column:multiple_values" json:"multiple_values"`
	Ismappingof    string `gorm:"column:ismappingof" json:"ismappingof"`
}

// TableName Mapping's table name
func (*Mapping) TableName() string {
	return TableNameMapping
}
