// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMappingElement = "mapping_element"

// MappingElement mapped from table <mapping_element>
type MappingElement struct {
	MappingInstanceID string `gorm:"column:mapping_instance_id;primaryKey" json:"mapping_instance_id"`
	ElementInstanceID string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName MappingElement's table name
func (*MappingElement) TableName() string {
	return TableNameMappingElement
}
