// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMetadataGroup = "metadata_group"

// MetadataGroup mapped from table <metadata_group>
type MetadataGroup struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	Name        string `gorm:"column:name" json:"name"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName MetadataGroup's table name
func (*MetadataGroup) TableName() string {
	return TableNameMetadataGroup
}
