// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMetadataUser = "metadata_user"

// MetadataUser mapped from table <metadata_user>
type MetadataUser struct {
	AuthIdentifier string `gorm:"column:auth_identifier;primaryKey" json:"auth_identifier"`
	Familyname     string `gorm:"column:familyname" json:"familyname"`
	Givenname      string `gorm:"column:givenname" json:"givenname"`
	Email          string `gorm:"column:email" json:"email"`
	Isadmin        string `gorm:"column:isadmin" json:"isadmin"`
}

// TableName MetadataUser's table name
func (*MetadataUser) TableName() string {
	return TableNameMetadataUser
}
