// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMetadataGroupUser = "metadata_group_user"

// MetadataGroupUser mapped from table <metadata_group_user>
type MetadataGroupUser struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`
	AuthIdentifier string `gorm:"column:auth_identifier;not null" json:"auth_identifier"`
	GroupID        string `gorm:"column:group_id" json:"group_id"`
	RequestStatus  string `gorm:"column:request_status" json:"request_status"`
	Role           string `gorm:"column:role" json:"role"`
}

// TableName MetadataGroupUser's table name
func (*MetadataGroupUser) TableName() string {
	return TableNameMetadataGroupUser
}
