// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOntology = "ontologies"

// Ontology mapped from table <ontologies>
type Ontology struct {
	ID      string `gorm:"column:id;primaryKey" json:"id"`
	Name    string `gorm:"column:name" json:"name"`
	Type    string `gorm:"column:type" json:"type"`
	Content string `gorm:"column:content" json:"content"`
}

// TableName Ontology's table name
func (*Ontology) TableName() string {
	return TableNameOntology
}
