// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOperationWebservice = "operation_webservice"

// OperationWebservice mapped from table <operation_webservice>
type OperationWebservice struct {
	OperationInstanceID  string `gorm:"column:operation_instance_id;primaryKey" json:"operation_instance_id"`
	WebserviceInstanceID string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
}

// TableName OperationWebservice's table name
func (*OperationWebservice) TableName() string {
	return TableNameOperationWebservice
}
