// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOperationMapping = "operation_mapping"

// OperationMapping mapped from table <operation_mapping>
type OperationMapping struct {
	OperationInstanceID string `gorm:"column:operation_instance_id;primaryKey" json:"operation_instance_id"`
	MappingInstanceID   string `gorm:"column:mapping_instance_id;primaryKey" json:"mapping_instance_id"`
}

// TableName OperationMapping's table name
func (*OperationMapping) TableName() string {
	return TableNameOperationMapping
}
