// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOperation = "operation"

// Operation mapped from table <operation>
type Operation struct {
	InstanceID string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string `gorm:"column:meta_id" json:"meta_id"`
	UID        string `gorm:"column:uid" json:"uid"`
	VersionID  string `gorm:"column:version_id" json:"version_id"`
	Method     string `gorm:"column:method" json:"method"`
	Template   string `gorm:"column:template" json:"template"`
}

// TableName Operation's table name
func (*Operation) TableName() string {
	return TableNameOperation
}
