// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOperationElement = "operation_element"

// OperationElement mapped from table <operation_element>
type OperationElement struct {
	OperationInstanceID string `gorm:"column:operation_instance_id;primaryKey" json:"operation_instance_id"`
	ElementInstanceID   string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName OperationElement's table name
func (*OperationElement) TableName() string {
	return TableNameOperationElement
}
