// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOperationDistribution = "operation_distribution"

// OperationDistribution mapped from table <operation_distribution>
type OperationDistribution struct {
	OperationInstanceID    string `gorm:"column:operation_instance_id;primaryKey" json:"operation_instance_id"`
	DistributionInstanceID string `gorm:"column:distribution_instance_id;primaryKey" json:"distribution_instance_id"`
}

// TableName OperationDistribution's table name
func (*OperationDistribution) TableName() string {
	return TableNameOperationDistribution
}
