// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganization = "organization"

// Organization mapped from table <organization>
type Organization struct {
	InstanceID string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string `gorm:"column:meta_id" json:"meta_id"`
	UID        string `gorm:"column:uid" json:"uid"`
	VersionID  string `gorm:"column:version_id" json:"version_id"`
	Acronym    string `gorm:"column:acronym" json:"acronym"`
	Legalname  string `gorm:"column:legalname" json:"legalname"`
	Leicode    string `gorm:"column:leicode" json:"leicode"`
	AddressID  string `gorm:"column:address_id" json:"address_id"`
	Logo       string `gorm:"column:logo" json:"logo"`
	URL        string `gorm:"column:url" json:"url"`
	Type       string `gorm:"column:type" json:"type"`
	Maturity   string `gorm:"column:maturity" json:"maturity"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
