// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganizationOwn = "organization_owns"

// OrganizationOwn mapped from table <organization_owns>
type OrganizationOwn struct {
	OrganizationInstanceID string `gorm:"column:organization_instance_id;primaryKey" json:"organization_instance_id"`
	EntityInstanceID       string `gorm:"column:entity_instance_id;not null" json:"entity_instance_id"`
	ResourceEntity         string `gorm:"column:resource_entity;not null" json:"resource_entity"`
}

// TableName OrganizationOwn's table name
func (*OrganizationOwn) TableName() string {
	return TableNameOrganizationOwn
}
