// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganizationMemberof = "organization_memberof"

// OrganizationMemberof mapped from table <organization_memberof>
type OrganizationMemberof struct {
	Organization1InstanceID string `gorm:"column:organization1_instance_id;primaryKey" json:"organization1_instance_id"`
	Organization2InstanceID string `gorm:"column:organization2_instance_id;primaryKey" json:"organization2_instance_id"`
}

// TableName OrganizationMemberof's table name
func (*OrganizationMemberof) TableName() string {
	return TableNameOrganizationMemberof
}
