// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganizationIdentifier = "organization_identifier"

// OrganizationIdentifier mapped from table <organization_identifier>
type OrganizationIdentifier struct {
	OrganizationInstanceID string `gorm:"column:organization_instance_id;primaryKey" json:"organization_instance_id"`
	IdentifierInstanceID   string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName OrganizationIdentifier's table name
func (*OrganizationIdentifier) TableName() string {
	return TableNameOrganizationIdentifier
}
