// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganizationContactpoint = "organization_contactpoint"

// OrganizationContactpoint mapped from table <organization_contactpoint>
type OrganizationContactpoint struct {
	OrganizationInstanceID string `gorm:"column:organization_instance_id;primaryKey" json:"organization_instance_id"`
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName OrganizationContactpoint's table name
func (*OrganizationContactpoint) TableName() string {
	return TableNameOrganizationContactpoint
}
