// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganizationElement = "organization_element"

// OrganizationElement mapped from table <organization_element>
type OrganizationElement struct {
	OrganizationInstanceID string `gorm:"column:organization_instance_id;primaryKey" json:"organization_instance_id"`
	ElementInstanceID      string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName OrganizationElement's table name
func (*OrganizationElement) TableName() string {
	return TableNameOrganizationElement
}
