// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameParameter = "parameter"

// Parameter mapped from table <parameter>
type Parameter struct {
	InstanceID     string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID         string `gorm:"column:meta_id" json:"meta_id"`
	UID            string `gorm:"column:uid" json:"uid"`
	VersionID      string `gorm:"column:version_id" json:"version_id"`
	Encodingformat string `gorm:"column:encodingformat" json:"encodingformat"`
	Conformsto     string `gorm:"column:conformsto" json:"conformsto"`
	Action         string `gorm:"column:action" json:"action"`
}

// TableName Parameter's table name
func (*Parameter) TableName() string {
	return TableNameParameter
}
