// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePersonIdentifier = "person_identifier"

// PersonIdentifier mapped from table <person_identifier>
type PersonIdentifier struct {
	PersonInstanceID     string `gorm:"column:person_instance_id;primaryKey" json:"person_instance_id"`
	IdentifierInstanceID string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName PersonIdentifier's table name
func (*PersonIdentifier) TableName() string {
	return TableNamePersonIdentifier
}
