// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePerson = "person"

// Person mapped from table <person>
type Person struct {
	InstanceID     string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID         string `gorm:"column:meta_id" json:"meta_id"`
	UID            string `gorm:"column:uid" json:"uid"`
	VersionID      string `gorm:"column:version_id" json:"version_id"`
	Familyname     string `gorm:"column:familyname" json:"familyname"`
	Givenname      string `gorm:"column:givenname" json:"givenname"`
	Qualifications string `gorm:"column:qualifications" json:"qualifications"`
	Cvurl          string `gorm:"column:cvurl" json:"cvurl"`
	AddressID      string `gorm:"column:address_id" json:"address_id"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
