// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePersonContactpoint = "person_contactpoint"

// PersonContactpoint mapped from table <person_contactpoint>
type PersonContactpoint struct {
	PersonInstanceID       string `gorm:"column:person_instance_id;primaryKey" json:"person_instance_id"`
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName PersonContactpoint's table name
func (*PersonContactpoint) TableName() string {
	return TableNamePersonContactpoint
}
