// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePersonElement = "person_element"

// PersonElement mapped from table <person_element>
type PersonElement struct {
	PersonInstanceID  string `gorm:"column:person_instance_id;primaryKey" json:"person_instance_id"`
	ElementInstanceID string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName PersonElement's table name
func (*PersonElement) TableName() string {
	return TableNamePersonElement
}
