// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePublication = "publication"

// Publication mapped from table <publication>
type Publication struct {
	InstanceID   string    `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID       string    `gorm:"column:meta_id" json:"meta_id"`
	UID          string    `gorm:"column:uid" json:"uid"`
	VersionID    string    `gorm:"column:version_id" json:"version_id"`
	Name         string    `gorm:"column:name" json:"name"`
	Published    time.Time `gorm:"column:published" json:"published"`
	Abstracttext string    `gorm:"column:abstracttext" json:"abstracttext"`
	Licenseurl   string    `gorm:"column:licenseurl" json:"licenseurl"`
	Keywords     string    `gorm:"column:keywords" json:"keywords"`
	Issn         string    `gorm:"column:issn" json:"issn"`
	Pages        int32     `gorm:"column:pages" json:"pages"`
	Volumenumber string    `gorm:"column:volumenumber" json:"volumenumber"`
	Author       string    `gorm:"column:author" json:"author"`
	Publisher    string    `gorm:"column:publisher" json:"publisher"`
}

// TableName Publication's table name
func (*Publication) TableName() string {
	return TableNamePublication
}
