// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePublicationIdentifier = "publication_identifier"

// PublicationIdentifier mapped from table <publication_identifier>
type PublicationIdentifier struct {
	PublicationInstanceID string `gorm:"column:publication_instance_id;primaryKey" json:"publication_instance_id"`
	IdentifierInstanceID  string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName PublicationIdentifier's table name
func (*PublicationIdentifier) TableName() string {
	return TableNamePublicationIdentifier
}
