// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePublicationContributor = "publication_contributor"

// PublicationContributor mapped from table <publication_contributor>
type PublicationContributor struct {
	PersonInstanceID      string `gorm:"column:person_instance_id;primaryKey" json:"person_instance_id"`
	PublicationInstanceID string `gorm:"column:publication_instance_id;primaryKey" json:"publication_instance_id"`
}

// TableName PublicationContributor's table name
func (*PublicationContributor) TableName() string {
	return TableNamePublicationContributor
}
