// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuantitativevalue = "quantitativevalue"

// Quantitativevalue mapped from table <quantitativevalue>
type Quantitativevalue struct {
	InstanceID string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string `gorm:"column:meta_id" json:"meta_id"`
	UID        string `gorm:"column:uid" json:"uid"`
	VersionID  string `gorm:"column:version_id" json:"version_id"`
	Unitcode   string `gorm:"column:unitcode" json:"unitcode"`
	Value      string `gorm:"column:value" json:"value"`
}

// TableName Quantitativevalue's table name
func (*Quantitativevalue) TableName() string {
	return TableNameQuantitativevalue
}
