// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceSpatial = "service_spatial"

// ServiceSpatial mapped from table <service_spatial>
type ServiceSpatial struct {
	ServiceInstanceID string `gorm:"column:service_instance_id;primaryKey" json:"service_instance_id"`
	SpatialInstanceID string `gorm:"column:spatial_instance_id;primaryKey" json:"spatial_instance_id"`
}

// TableName ServiceSpatial's table name
func (*ServiceSpatial) TableName() string {
	return TableNameServiceSpatial
}
