// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceIdentifier = "service_identifier"

// ServiceIdentifier mapped from table <service_identifier>
type ServiceIdentifier struct {
	ServiceInstanceID    string `gorm:"column:service_instance_id;primaryKey" json:"service_instance_id"`
	IdentifierInstanceID string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName ServiceIdentifier's table name
func (*ServiceIdentifier) TableName() string {
	return TableNameServiceIdentifier
}
