// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceTemporal = "service_temporal"

// ServiceTemporal mapped from table <service_temporal>
type ServiceTemporal struct {
	ServiceInstanceID  string `gorm:"column:service_instance_id;primaryKey" json:"service_instance_id"`
	TemporalInstanceID string `gorm:"column:temporal_instance_id;primaryKey" json:"temporal_instance_id"`
}

// TableName ServiceTemporal's table name
func (*ServiceTemporal) TableName() string {
	return TableNameServiceTemporal
}
