// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceProvider = "service_provider"

// ServiceProvider mapped from table <service_provider>
type ServiceProvider struct {
	ServiceInstanceID string `gorm:"column:service_instance_id;primaryKey" json:"service_instance_id"`
	EntityInstanceID  string `gorm:"column:entity_instance_id;not null" json:"entity_instance_id"`
	ResourceEntity    string `gorm:"column:resource_entity;not null" json:"resource_entity"`
}

// TableName ServiceProvider's table name
func (*ServiceProvider) TableName() string {
	return TableNameServiceProvider
}
