// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceCategory = "service_category"

// ServiceCategory mapped from table <service_category>
type ServiceCategory struct {
	CategoryInstanceID string `gorm:"column:category_instance_id;primaryKey" json:"category_instance_id"`
	ServiceInstanceID  string `gorm:"column:service_instance_id;primaryKey" json:"service_instance_id"`
}

// TableName ServiceCategory's table name
func (*ServiceCategory) TableName() string {
	return TableNameServiceCategory
}
