// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameService = "service"

// Service mapped from table <service>
type Service struct {
	InstanceID      string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID          string `gorm:"column:meta_id" json:"meta_id"`
	UID             string `gorm:"column:uid" json:"uid"`
	VersionID       string `gorm:"column:version_id" json:"version_id"`
	Name            string `gorm:"column:name" json:"name"`
	Description     string `gorm:"column:description" json:"description"`
	Type            string `gorm:"column:type" json:"type"`
	Pageurl         string `gorm:"column:pageurl" json:"pageurl"`
	Keywords        string `gorm:"column:keywords" json:"keywords"`
	Servicecontract string `gorm:"column:servicecontract" json:"servicecontract"`
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
