// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameServiceContactpoint = "service_contactpoint"

// ServiceContactpoint mapped from table <service_contactpoint>
type ServiceContactpoint struct {
	ServiceInstanceID      string `gorm:"column:service_instance_id;primaryKey" json:"service_instance_id"`
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName ServiceContactpoint's table name
func (*ServiceContactpoint) TableName() string {
	return TableNameServiceContactpoint
}
