// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwaresourcecodeElement = "softwaresourcecode_element"

// SoftwaresourcecodeElement mapped from table <softwaresourcecode_element>
type SoftwaresourcecodeElement struct {
	SoftwaresourcecodeInstanceID string `gorm:"column:softwaresourcecode_instance_id;primaryKey" json:"softwaresourcecode_instance_id"`
	ElementInstanceID            string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName SoftwaresourcecodeElement's table name
func (*SoftwaresourcecodeElement) TableName() string {
	return TableNameSoftwaresourcecodeElement
}
