// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwareapplicationIdentifier = "softwareapplication_identifier"

// SoftwareapplicationIdentifier mapped from table <softwareapplication_identifier>
type SoftwareapplicationIdentifier struct {
	SoftwareapplicationInstanceID string `gorm:"column:softwareapplication_instance_id;primaryKey" json:"softwareapplication_instance_id"`
	IdentifierInstanceID          string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName SoftwareapplicationIdentifier's table name
func (*SoftwareapplicationIdentifier) TableName() string {
	return TableNameSoftwareapplicationIdentifier
}
