// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwareapplicationContactpoint = "softwareapplication_contactpoint"

// SoftwareapplicationContactpoint mapped from table <softwareapplication_contactpoint>
type SoftwareapplicationContactpoint struct {
	SoftwareapplicationInstanceID string `gorm:"column:softwareapplication_instance_id;primaryKey" json:"softwareapplication_instance_id"`
	ContactpointInstanceID        string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName SoftwareapplicationContactpoint's table name
func (*SoftwareapplicationContactpoint) TableName() string {
	return TableNameSoftwareapplicationContactpoint
}
