// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwareapplicationOperation = "softwareapplication_operation"

// SoftwareapplicationOperation mapped from table <softwareapplication_operation>
type SoftwareapplicationOperation struct {
	SoftwareapplicationInstanceID string `gorm:"column:softwareapplication_instance_id;primaryKey" json:"softwareapplication_instance_id"`
	OperationInstanceID           string `gorm:"column:operation_instance_id;primaryKey" json:"operation_instance_id"`
}

// TableName SoftwareapplicationOperation's table name
func (*SoftwareapplicationOperation) TableName() string {
	return TableNameSoftwareapplicationOperation
}
