// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwareapplication = "softwareapplication"

// Softwareapplication mapped from table <softwareapplication>
type Softwareapplication struct {
	InstanceID       string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID           string `gorm:"column:meta_id" json:"meta_id"`
	UID              string `gorm:"column:uid" json:"uid"`
	VersionID        string `gorm:"column:version_id" json:"version_id"`
	Name             string `gorm:"column:name" json:"name"`
	Description      string `gorm:"column:description" json:"description"`
	Downloadurl      string `gorm:"column:downloadurl" json:"downloadurl"`
	Licenseurl       string `gorm:"column:licenseurl" json:"licenseurl"`
	Softwareversion  string `gorm:"column:softwareversion" json:"softwareversion"`
	Keywords         string `gorm:"column:keywords" json:"keywords"`
	Requirements     string `gorm:"column:requirements" json:"requirements"`
	Installurl       string `gorm:"column:installurl" json:"installurl"`
	Mainentityofpage string `gorm:"column:mainentityofpage" json:"mainentityofpage"`
}

// TableName Softwareapplication's table name
func (*Softwareapplication) TableName() string {
	return TableNameSoftwareapplication
}
