// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwareapplicationCategory = "softwareapplication_category"

// SoftwareapplicationCategory mapped from table <softwareapplication_category>
type SoftwareapplicationCategory struct {
	CategoryInstanceID            string `gorm:"column:category_instance_id;primaryKey" json:"category_instance_id"`
	SoftwareapplicationInstanceID string `gorm:"column:softwareapplication_instance_id;primaryKey" json:"softwareapplication_instance_id"`
}

// TableName SoftwareapplicationCategory's table name
func (*SoftwareapplicationCategory) TableName() string {
	return TableNameSoftwareapplicationCategory
}
