// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwaresourcecodeContactpoint = "softwaresourcecode_contactpoint"

// SoftwaresourcecodeContactpoint mapped from table <softwaresourcecode_contactpoint>
type SoftwaresourcecodeContactpoint struct {
	SoftwaresourcecodeInstanceID string `gorm:"column:softwaresourcecode_instance_id;primaryKey" json:"softwaresourcecode_instance_id"`
	ContactpointInstanceID       string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName SoftwaresourcecodeContactpoint's table name
func (*SoftwaresourcecodeContactpoint) TableName() string {
	return TableNameSoftwaresourcecodeContactpoint
}
