// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwaresourcecode = "softwaresourcecode"

// Softwaresourcecode mapped from table <softwaresourcecode>
type Softwaresourcecode struct {
	InstanceID       string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID           string `gorm:"column:meta_id" json:"meta_id"`
	UID              string `gorm:"column:uid" json:"uid"`
	VersionID        string `gorm:"column:version_id" json:"version_id"`
	Name             string `gorm:"column:name" json:"name"`
	Description      string `gorm:"column:description" json:"description"`
	Licenseurl       string `gorm:"column:licenseurl" json:"licenseurl"`
	Downloadurl      string `gorm:"column:downloadurl" json:"downloadurl"`
	Runtimeplatform  string `gorm:"column:runtimeplatform" json:"runtimeplatform"`
	Softwareversion  string `gorm:"column:softwareversion" json:"softwareversion"`
	Keywords         string `gorm:"column:keywords" json:"keywords"`
	Coderepository   string `gorm:"column:coderepository" json:"coderepository"`
	Mainentityofpage string `gorm:"column:mainentityofpage" json:"mainentityofpage"`
}

// TableName Softwaresourcecode's table name
func (*Softwaresourcecode) TableName() string {
	return TableNameSoftwaresourcecode
}
