// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwaresourcecodeIdentifier = "softwaresourcecode_identifier"

// SoftwaresourcecodeIdentifier mapped from table <softwaresourcecode_identifier>
type SoftwaresourcecodeIdentifier struct {
	SoftwaresourcecodeInstanceID string `gorm:"column:softwaresourcecode_instance_id;primaryKey" json:"softwaresourcecode_instance_id"`
	IdentifierInstanceID         string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName SoftwaresourcecodeIdentifier's table name
func (*SoftwaresourcecodeIdentifier) TableName() string {
	return TableNameSoftwaresourcecodeIdentifier
}
