// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSoftwaresourcecodeCategory = "softwaresourcecode_category"

// SoftwaresourcecodeCategory mapped from table <softwaresourcecode_category>
type SoftwaresourcecodeCategory struct {
	CategoryInstanceID           string `gorm:"column:category_instance_id;primaryKey" json:"category_instance_id"`
	SoftwaresourcecodeInstanceID string `gorm:"column:softwaresourcecode_instance_id;primaryKey" json:"softwaresourcecode_instance_id"`
}

// TableName SoftwaresourcecodeCategory's table name
func (*SoftwaresourcecodeCategory) TableName() string {
	return TableNameSoftwaresourcecodeCategory
}
