// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpatial = "spatial"

// Spatial mapped from table <spatial>
type Spatial struct {
	InstanceID string `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string `gorm:"column:meta_id" json:"meta_id"`
	UID        string `gorm:"column:uid" json:"uid"`
	VersionID  string `gorm:"column:version_id" json:"version_id"`
	Location   string `gorm:"column:location" json:"location"`
}

// TableName Spatial's table name
func (*Spatial) TableName() string {
	return TableNameSpatial
}
