// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemporal = "temporal"

// Temporal mapped from table <temporal>
type Temporal struct {
	InstanceID string    `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID     string    `gorm:"column:meta_id" json:"meta_id"`
	UID        string    `gorm:"column:uid" json:"uid"`
	VersionID  string    `gorm:"column:version_id" json:"version_id"`
	Startdate  time.Time `gorm:"column:startdate" json:"startdate"`
	Enddate    time.Time `gorm:"column:enddate" json:"enddate"`
}

// TableName Temporal's table name
func (*Temporal) TableName() string {
	return TableNameTemporal
}
