// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUsLex = "us_lex"

// UsLex mapped from table <us_lex>
type UsLex struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Seq      int32  `gorm:"column:seq" json:"seq"`
	Word     string `gorm:"column:word" json:"word"`
	Stdword  string `gorm:"column:stdword" json:"stdword"`
	Token    int32  `gorm:"column:token" json:"token"`
	IsCustom bool   `gorm:"column:is_custom;not null;default:true" json:"is_custom"`
}

// TableName UsLex's table name
func (*UsLex) TableName() string {
	return TableNameUsLex
}
