// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUsRule = "us_rules"

// UsRule mapped from table <us_rules>
type UsRule struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Rule     string `gorm:"column:rule" json:"rule"`
	IsCustom bool   `gorm:"column:is_custom;not null;default:true" json:"is_custom"`
}

// TableName UsRule's table name
func (*UsRule) TableName() string {
	return TableNameUsRule
}
