// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVersioningstatus = "versioningstatus"

// Versioningstatus mapped from table <versioningstatus>
type Versioningstatus struct {
	VersionID        string    `gorm:"column:version_id;primaryKey" json:"version_id"`
	InstanceID       string    `gorm:"column:instance_id" json:"instance_id"`
	MetaID           string    `gorm:"column:meta_id" json:"meta_id"`
	UID              string    `gorm:"column:uid" json:"uid"`
	InstanceChangeID string    `gorm:"column:instance_change_id" json:"instance_change_id"`
	Provenance       string    `gorm:"column:provenance" json:"provenance"`
	EditorID         string    `gorm:"column:editor_id" json:"editor_id"`
	ReviewerID       string    `gorm:"column:reviewer_id" json:"reviewer_id"`
	ReviewComment    string    `gorm:"column:review_comment" json:"review_comment"`
	ChangeComment    string    `gorm:"column:change_comment" json:"change_comment"`
	ChangeTimestamp  time.Time `gorm:"column:change_timestamp" json:"change_timestamp"`
	Version          string    `gorm:"column:version" json:"version"`
	Status           string    `gorm:"column:status" json:"status"`
}

// TableName Versioningstatus's table name
func (*Versioningstatus) TableName() string {
	return TableNameVersioningstatus
}
