// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceIdentifier = "webservice_identifier"

// WebserviceIdentifier mapped from table <webservice_identifier>
type WebserviceIdentifier struct {
	WebserviceInstanceID string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
	IdentifierInstanceID string `gorm:"column:identifier_instance_id;primaryKey" json:"identifier_instance_id"`
}

// TableName WebserviceIdentifier's table name
func (*WebserviceIdentifier) TableName() string {
	return TableNameWebserviceIdentifier
}
