// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWebservice = "webservice"

// Webservice mapped from table <webservice>
type Webservice struct {
	InstanceID       string    `gorm:"column:instance_id;primaryKey" json:"instance_id"`
	MetaID           string    `gorm:"column:meta_id" json:"meta_id"`
	UID              string    `gorm:"column:uid" json:"uid"`
	VersionID        string    `gorm:"column:version_id" json:"version_id"`
	Schemaidentifier string    `gorm:"column:schemaidentifier" json:"schemaidentifier"`
	Description      string    `gorm:"column:description" json:"description"`
	Name             string    `gorm:"column:name" json:"name"`
	Entrypoint       string    `gorm:"column:entrypoint" json:"entrypoint"`
	Datapublished    time.Time `gorm:"column:datapublished" json:"datapublished"`
	Datamodified     time.Time `gorm:"column:datamodified" json:"datamodified"`
	Keywords         string    `gorm:"column:keywords" json:"keywords"`
	License          string    `gorm:"column:license" json:"license"`
	Provider         string    `gorm:"column:provider" json:"provider"`
	Aaaitypes        string    `gorm:"column:aaaitypes" json:"aaaitypes"`
}

// TableName Webservice's table name
func (*Webservice) TableName() string {
	return TableNameWebservice
}
