// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceElement = "webservice_element"

// WebserviceElement mapped from table <webservice_element>
type WebserviceElement struct {
	WebserviceInstanceID string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
	ElementInstanceID    string `gorm:"column:element_instance_id;primaryKey" json:"element_instance_id"`
}

// TableName WebserviceElement's table name
func (*WebserviceElement) TableName() string {
	return TableNameWebserviceElement
}
