// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceSpatial = "webservice_spatial"

// WebserviceSpatial mapped from table <webservice_spatial>
type WebserviceSpatial struct {
	WebserviceInstanceID string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
	SpatialInstanceID    string `gorm:"column:spatial_instance_id;primaryKey" json:"spatial_instance_id"`
}

// TableName WebserviceSpatial's table name
func (*WebserviceSpatial) TableName() string {
	return TableNameWebserviceSpatial
}
