// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceCategory = "webservice_category"

// WebserviceCategory mapped from table <webservice_category>
type WebserviceCategory struct {
	CategoryInstanceID   string `gorm:"column:category_instance_id;primaryKey" json:"category_instance_id"`
	WebserviceInstanceID string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
}

// TableName WebserviceCategory's table name
func (*WebserviceCategory) TableName() string {
	return TableNameWebserviceCategory
}
