// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceRelation = "webservice_relation"

// WebserviceRelation mapped from table <webservice_relation>
type WebserviceRelation struct {
	WebserviceInstanceID string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
	EntityInstanceID     string `gorm:"column:entity_instance_id;not null" json:"entity_instance_id"`
	ResourceEntity       string `gorm:"column:resource_entity;not null" json:"resource_entity"`
}

// TableName WebserviceRelation's table name
func (*WebserviceRelation) TableName() string {
	return TableNameWebserviceRelation
}
