// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceTemporal = "webservice_temporal"

// WebserviceTemporal mapped from table <webservice_temporal>
type WebserviceTemporal struct {
	WebserviceInstanceID string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
	TemporalInstanceID   string `gorm:"column:temporal_instance_id;primaryKey" json:"temporal_instance_id"`
}

// TableName WebserviceTemporal's table name
func (*WebserviceTemporal) TableName() string {
	return TableNameWebserviceTemporal
}
