// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceDistribution = "webservice_distribution"

// WebserviceDistribution mapped from table <webservice_distribution>
type WebserviceDistribution struct {
	DistributionInstanceID string `gorm:"column:distribution_instance_id;primaryKey" json:"distribution_instance_id"`
	WebserviceInstanceID   string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
}

// TableName WebserviceDistribution's table name
func (*WebserviceDistribution) TableName() string {
	return TableNameWebserviceDistribution
}
