// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWebserviceContactpoint = "webservice_contactpoint"

// WebserviceContactpoint mapped from table <webservice_contactpoint>
type WebserviceContactpoint struct {
	WebserviceInstanceID   string `gorm:"column:webservice_instance_id;primaryKey" json:"webservice_instance_id"`
	ContactpointInstanceID string `gorm:"column:contactpoint_instance_id;primaryKey" json:"contactpoint_instance_id"`
}

// TableName WebserviceContactpoint's table name
func (*WebserviceContactpoint) TableName() string {
	return TableNameWebserviceContactpoint
}
